"""ha_model.py -- the hidden-action marketplace.

The platform does NOT observe a merchant's fabrication level. It observes a noisy signal vector
generated by that fabrication, and it commits, in public and in advance, to a reputation/penalty rule
that is a function of the signal only. Everything the platform is allowed to know is derived from the
signal; everything else is either the merchant's own private information or exists only for the
evaluator writing the paper.

This module is the single source of truth for:
  * the primitives (types, actions, demand, traffic);
  * the SIGNAL PROCESS  z_it ~ P(z | q_i, f_it, state)  -- complaints, refunds, audit flags, sales;
  * the SIGNAL-CONTINGENT POLICY  r_{i,t+1} = g(r_it, z_it; kappa, tau)  and its extended variant;
  * the stationary restricted payoffs used by every benchmark;
  * exact enumeration of the 21^4 joint action space (pure equilibria, first best).

Relation to the earlier code. The demand system, the complaint model, the threshold penalty and the
reputation recursion are byte-for-byte the same economics as `equilibrium.py` / `hetero.py` in the
Balance-6..9 line, with the SAME constants. The market draw is the same draw. What changes is not the
economics but the INFORMATION: the earlier interfaces handed the merchant a payoff table that only an
oracle could build, and this module removes that oracle. Two signals are added (refunds, audit flags)
because a realistic platform sees more than one number; neither of them changes the base policy family,
so every earlier (kappa, tau) result remains directly comparable.

No API, no network, pure numpy.
"""

from __future__ import annotations

import json
import math
from dataclasses import dataclass, field
from pathlib import Path

import numpy as np

HERE = Path(__file__).resolve().parent
PKG = HERE.parent
_POOL = None


def catalog_pool():
    global _POOL
    if _POOL is None:
        _POOL = json.loads((PKG / "input_data" / "catalog_types.json").read_text())["pool"]
    return _POOL


# ==================================================================================================
# primitives
# ==================================================================================================
@dataclass
class Config:
    """Frozen constants. Identical to the Balance-9 market spec unless the comment says otherwise."""

    m: int = 4                  # merchants per market
    alpha: float = 3.0          # appeal weight in the logit
    beta: float = 1.5           # reputation weight in the logit
    gamma: float = 1.0          # price weight in the logit
    Q0: float = 1.0             # base traffic
    eta_r: float = 0.20         # reputation recovery toward 1
    cs: float = 0.60            # fabrication -> complaint slope: theta(f, b) = clip(b + cs f, 0, 1)
    N_obs: int = 40             # audited transactions per merchant per round (complaint sample size)
    Nf: int = 21                # action grid 0, 0.05, ..., 1.00
    R: int = 31                 # reputation grid for the stationary chain
    omega: float = 0.50         # catalog overlap -> outside utility
    lam: float = 1.00           # trust erosion in Q = Q0 exp(-lam * mean f)
    W0_BASE: float = -1.0
    W0_SPREAD: float = 4.0
    margin_frac: float = 0.5    # merchant margin = margin_frac * p (Balance-6..9 convention)

    # --- signal channels that the earlier code did not have -------------------------------------
    phi_refund: float = 0.50    # P(refund | complaint). A THINNING of the complaint count, hence a
                                # garbling: it carries no information about f beyond d. Proposition 7.
    N_audit: int = 5            # listings sampled by content moderation per merchant per round
    psi0: float = 0.02          # audit hit rate for a fully honest listing (false-flag floor)
    psi1: float = 0.25          # audit hit rate slope in f (second informative channel)

    fgrid: np.ndarray = field(init=False)
    rgrid: np.ndarray = field(init=False)

    def __post_init__(self):
        self.fgrid = np.linspace(0.0, 1.0, self.Nf)
        self.rgrid = np.linspace(0.0, 1.0, self.R)

    @property
    def w0(self) -> float:
        return self.W0_BASE + self.W0_SPREAD * (1.0 - self.omega)


# baseline complaint propensity grid; a merchant's drawn b is snapped to this grid so the stationary
# reputation table is a small precomputable object.
B_GRID = np.linspace(0.01, 0.15, 15)

# the two policies carried over from Balance-9 so the arms stay comparable
POLICIES = {"P_GMV": (0.5, 0.20), "P_robust": (4.0, 0.30)}

# the finite policy class searched for the policy-class second best. This is a FINITE GRID, and every
# statement derived from it is a statement about this grid, never about all conceivable mechanisms.
KAPPA_GRID = (0.0, 0.25, 0.5, 1.0, 2.0, 4.0, 8.0, 16.0)
TAU_GRID = (0.02, 0.05, 0.10, 0.15, 0.20, 0.25, 0.30, 0.40)
POLICY_CLASS = tuple((float(k), float(t)) for k in KAPPA_GRID for t in TAU_GRID)

# extended class: complaint threshold penalty PLUS an audit-flag threshold penalty
KAPPA_A_GRID = (0.0, 0.05, 0.10, 0.20)
TAU_A_GRID = (0.0, 0.2, 0.4)


@dataclass
class Market:
    """One drawn market. `q` and `b` are MERCHANT-PRIVATE: the platform never sees them."""

    seed: int
    q: np.ndarray               # honest quality per merchant
    p: np.ndarray               # normalised price per merchant
    b: np.ndarray               # baseline complaint propensity (continuous draw)
    bidx: np.ndarray            # index of b snapped onto B_GRID

    @property
    def m(self) -> int:
        return len(self.q)


def draw_market(cfg: Config, seed: int, base: int = 1000) -> Market:
    """Draw market `seed`. Same draw order and same generator as hetero.draw_market_seeded, so a
    market index means the same market it has always meant."""
    rng = np.random.default_rng(base + seed)
    pool = catalog_pool()
    idx = rng.choice(len(pool), size=cfg.m, replace=False)
    q = np.array([pool[i]["q"] for i in idx], dtype=float)
    p = np.array([pool[i]["p_norm"] for i in idx], dtype=float)
    b = np.clip(rng.beta(2, 5, cfg.m) * 0.15, 0.01, 0.15)
    bidx = np.array([int(np.argmin(np.abs(B_GRID - v))) for v in b])
    return Market(seed=seed, q=q, p=p, b=b, bidx=bidx)


# ==================================================================================================
# the signal process   z_it ~ P(z | q_i, f_it, market state)
# ==================================================================================================
def theta(cfg: Config, f, b) -> np.ndarray:
    """Expected complaint rate per audited transaction."""
    return np.clip(np.asarray(b, dtype=float) + cfg.cs * np.asarray(f, dtype=float), 0.0, 1.0)


def psi(cfg: Config, f) -> np.ndarray:
    """Expected audit-flag rate per sampled listing."""
    return np.clip(cfg.psi0 + cfg.psi1 * np.asarray(f, dtype=float), 0.0, 1.0)


def binom_pmf(n: int, pr: float) -> np.ndarray:
    pr = min(max(float(pr), 1e-12), 1 - 1e-12)
    k = np.arange(n + 1)
    logc = np.array([math.lgamma(n + 1) - math.lgamma(kk + 1) - math.lgamma(n - kk + 1) for kk in k])
    return np.exp(logc + k * math.log(pr) + (n - k) * math.log(1 - pr))


def complaint_pmf(cfg: Config, f: float, b: float) -> np.ndarray:
    return binom_pmf(cfg.N_obs, float(theta(cfg, f, b)))


def audit_pmf(cfg: Config, f: float) -> np.ndarray:
    return binom_pmf(cfg.N_audit, float(psi(cfg, f)))


def sample_signal(cfg: Config, rng: np.random.Generator, f: float, b: float,
                  sales: float) -> dict:
    """Draw one round of platform-observable signals for one merchant.

    Returns ONLY quantities the platform is allowed to see. `f`, `b` and `q` go in; none of them
    comes out. This asymmetry is the whole point of the module.
    """
    d = int(rng.binomial(cfg.N_obs, float(theta(cfg, f, b))))
    refunds = int(rng.binomial(d, cfg.phi_refund)) if d > 0 else 0
    flags = int(rng.binomial(cfg.N_audit, float(psi(cfg, f))))
    return dict(transactions_sampled=cfg.N_obs, complaints=d, complaint_rate=d / cfg.N_obs,
                refunds=refunds, listings_audited=cfg.N_audit, audit_flags=flags,
                sales_volume=float(sales))


# ==================================================================================================
# the signal-contingent policy   r_{i,t+1} = g(r_it, z_it; kappa, tau)
# ==================================================================================================
def penalty_from_signal(kappa: float, tau: float, complaint_rate: float,
                        kappa_a: float = 0.0, tau_a: float = 0.0,
                        audit_rate: float = 0.0) -> float:
    """The published rule. It reads the signal and nothing else -- no q, no b, no f."""
    return (kappa * max(0.0, complaint_rate - tau)
            + kappa_a * max(0.0, audit_rate - tau_a))


def reputation_update(cfg: Config, r: float, pen: float) -> float:
    return float(np.clip(r + cfg.eta_r * (1.0 - r) - pen, 0.0, 1.0))


def _stationary_mean(cfg: Config, pmf_d: np.ndarray, pen_d: np.ndarray) -> float:
    """Stationary mean of r' = clip(r + eta_r(1-r) - P(count), 0, 1) on the R-point grid."""
    R, rgrid = cfg.R, cfg.rgrid
    T = np.zeros((R, R))
    for i, r in enumerate(rgrid):
        rp = np.clip(r + cfg.eta_r * (1 - r) - pen_d, 0.0, 1.0)
        idx = np.clip(np.round(rp * (R - 1)).astype(int), 0, R - 1)
        np.add.at(T[i], idx, pmf_d)
    pi = np.full(R, 1.0 / R)
    for _ in range(300):
        pi = pi @ T
    return float(pi @ rgrid)


def rbar_grid(cfg: Config, kappa: float, tau: float,
              kappa_a: float = 0.0, tau_a: float = 0.0) -> np.ndarray:
    """rbar[b_index, f_index] -- the stationary mean reputation the policy induces.

    This is the object the platform's mechanism acts through, and the ONLY channel by which a
    signal-contingent policy can move a merchant's incentives. If the signal does not move with f,
    this table is flat in f and the platform is powerless (Proposition 6).
    """
    Drate = np.arange(cfg.N_obs + 1) / cfg.N_obs
    Arate = np.arange(cfg.N_audit + 1) / cfg.N_audit
    out = np.zeros((len(B_GRID), cfg.Nf))
    for bi, b in enumerate(B_GRID):
        for fi, f in enumerate(cfg.fgrid):
            pen_d = kappa * np.maximum(0.0, Drate - tau)
            pmf_d = complaint_pmf(cfg, f, b)
            if kappa_a > 0.0:
                # the two channels are conditionally independent given f, so convolve the induced
                # penalty distributions rather than assuming one dominates
                pmf_a = audit_pmf(cfg, f)
                pen_a = kappa_a * np.maximum(0.0, Arate - tau_a)
                pen = (pen_d[:, None] + pen_a[None, :]).ravel()
                pmf = (pmf_d[:, None] * pmf_a[None, :]).ravel()
                order = np.argsort(pen)
                out[bi, fi] = _stationary_mean(cfg, pmf[order], pen[order])
            else:
                out[bi, fi] = _stationary_mean(cfg, pmf_d, pen_d)
    return out


def rbar_for_market(cfg: Config, mkt: Market, rg: np.ndarray) -> np.ndarray:
    """rbar[j, f_index] for the merchants of one market."""
    return rg[mkt.bidx, :]


# ==================================================================================================
# stationary restricted payoffs  (EVALUATOR-ONLY: they need q, p, b, and the rivals' true actions)
# ==================================================================================================
def profile_outcome(cfg: Config, mkt: Market, rbar_m: np.ndarray, fidx: np.ndarray) -> dict:
    """One joint action profile, evaluated at the stationary reputations it induces."""
    f = cfg.fgrid[fidx]
    r = rbar_m[np.arange(mkt.m), fidx]
    u = cfg.alpha * (mkt.q + (1 - mkt.q) * f) + cfg.beta * r - cfg.gamma * mkt.p
    den = math.exp(cfg.w0) + float(np.exp(u).sum())
    s = np.exp(u) / den
    Q = cfg.Q0 * math.exp(-cfg.lam * float(f.mean()))
    profit = cfg.margin_frac * mkt.p * Q * s
    return dict(f=f, r=r, share=s, Q=Q, profit=profit,
                GMV=float(Q * float((mkt.p * s).sum())),
                inside_share=float(s.sum()))


def enumerate_profiles(cfg: Config, mkt: Market, rbar_m: np.ndarray) -> dict:
    """EXACT enumeration of all Nf^m joint actions (21^4 = 194,481 for the frozen spec).

    Feasibility, measured not assumed: the whole computation is broadcast over five arrays of
    194,481 float64 (about 1.5 MB each), so a (seed, policy) pair costs tens of milliseconds. Exact
    first best and the exact set of pure equilibria are therefore affordable for every seed and every
    policy in the class, and no benchmark in this package relies on a heuristic search.
    """
    m, Nf = mkt.m, cfg.Nf
    shape = (Nf,) * m
    u = [cfg.alpha * (mkt.q[j] + (1 - mkt.q[j]) * cfg.fgrid) + cfg.beta * rbar_m[j]
         - cfg.gamma * mkt.p[j] for j in range(m)]
    exp_u = [np.exp(u[j]) for j in range(m)]

    def ax(j):
        sh = [1] * m
        sh[j] = Nf
        return tuple(sh)

    den = np.full(shape, math.exp(cfg.w0))
    fsum = np.zeros(shape)
    for j in range(m):
        den = den + exp_u[j].reshape(ax(j))
        fsum = fsum + cfg.fgrid.reshape(ax(j))
    Q = cfg.Q0 * np.exp(-cfg.lam * fsum / m)

    shares = [exp_u[j].reshape(ax(j)) / den for j in range(m)]
    profit = [cfg.margin_frac * mkt.p[j] * Q * shares[j] for j in range(m)]
    gmv = Q * sum(mkt.p[j] * shares[j] for j in range(m))
    return dict(profit=profit, GMV=gmv, Q=Q, shares=shares)


def pure_nash(cfg: Config, mkt: Market, rbar_m: np.ndarray, enum: dict = None,
              tie_tol: float = 1e-12) -> list:
    """Every pure-strategy Nash profile of the restricted stationary hidden-action game.

    Exhaustive, not iterative: a profile survives iff no merchant has a strictly profitable unilateral
    deviation, checked against the exact maximum over that merchant's own axis. Existence is therefore
    CERTIFIED per seed rather than assumed, and multiplicity is measured rather than hoped away.
    """
    if enum is None:
        enum = enumerate_profiles(cfg, mkt, rbar_m)
    ok = np.ones((cfg.Nf,) * mkt.m, dtype=bool)
    for j in range(mkt.m):
        best = enum["profit"][j].max(axis=j, keepdims=True)
        ok &= enum["profit"][j] >= best - tie_tol
    return [tuple(int(v) for v in idx) for idx in zip(*np.nonzero(ok))]


def best_response_dynamics(cfg: Config, mkt: Market, rbar_m: np.ndarray,
                           start: np.ndarray = None, iters: int = 200) -> tuple:
    """Gauss-Seidel best response, the same iteration hetero.hetero_equilibrium uses.

    Returned so the enumerated equilibrium set can be compared against what the historical solver
    would have reported; a disagreement is a finding, not a nuisance.
    """
    fidx = np.zeros(mkt.m, dtype=int) if start is None else np.array(start, dtype=int)
    seen, path = set(), [tuple(fidx)]
    for _ in range(iters):
        changed = False
        for j in range(mkt.m):
            cand = np.repeat(fidx[None, :], cfg.Nf, axis=0)
            cand[:, j] = np.arange(cfg.Nf)
            pr = np.array([profile_outcome(cfg, mkt, rbar_m, c)["profit"][j] for c in cand])
            bj = int(np.argmax(pr))
            if bj != fidx[j]:
                fidx[j] = bj
                changed = True
        key = tuple(fidx)
        path.append(key)
        if not changed:
            return fidx, path, "fixed_point"
        if key in seen:
            return fidx, path, "cycle"
        seen.add(key)
    return fidx, path, "iteration_limit"


def exploitability(cfg: Config, mkt: Market, rbar_m: np.ndarray, fidx: np.ndarray) -> np.ndarray:
    """eps_j = max_d V_j(d, f_-j) - V_j(f_j, f_-j) at the stationary restricted payoff.

    This is the hidden-action equilibrium regret. It is EVALUATOR-ONLY: computing it needs every
    merchant's true type and true action, which is exactly what the platform does not have.
    """
    fidx = np.array(fidx, dtype=int)
    base = profile_outcome(cfg, mkt, rbar_m, fidx)["profit"]
    eps = np.zeros(mkt.m)
    for j in range(mkt.m):
        best = base[j]
        for d in range(cfg.Nf):
            c = fidx.copy()
            c[j] = d
            best = max(best, profile_outcome(cfg, mkt, rbar_m, c)["profit"][j])
        eps[j] = best - base[j]
    return eps


# ==================================================================================================
# realised dynamics -- what an actual run does, round by round
# ==================================================================================================
def step(cfg: Config, mkt: Market, rng: np.random.Generator, r: np.ndarray, f: np.ndarray,
         kappa: float, tau: float, kappa_a: float = 0.0, tau_a: float = 0.0) -> dict:
    """One realised round: demand at the CURRENT reputation path, then signals, then the policy.

    Nothing here consults the stationary tables. Realised and projected quantities are produced by
    different functions on purpose, so that a report can never quietly substitute one for the other.
    """
    f = np.asarray(f, dtype=float)
    u = cfg.alpha * (mkt.q + (1 - mkt.q) * f) + cfg.beta * r - cfg.gamma * mkt.p
    den = math.exp(cfg.w0) + float(np.exp(u).sum())
    s = np.exp(u) / den
    Q = cfg.Q0 * math.exp(-cfg.lam * float(f.mean()))
    profit = cfg.margin_frac * mkt.p * Q * s
    gmv = float(Q * float((mkt.p * s).sum()))

    sig, pen, r_next = [], np.zeros(mkt.m), np.zeros(mkt.m)
    for j in range(mkt.m):
        z = sample_signal(cfg, rng, f[j], mkt.b[j], sales=float(Q * s[j]))
        pen[j] = penalty_from_signal(kappa, tau, z["complaint_rate"], kappa_a, tau_a,
                                     z["audit_flags"] / cfg.N_audit)
        z["penalty_applied"] = float(pen[j])
        sig.append(z)
        r_next[j] = reputation_update(cfg, float(r[j]), float(pen[j]))
    return dict(share=s, Q=Q, profit=profit, GMV=gmv, signals=sig, penalty=pen,
                r=r.copy(), r_next=r_next)


# ==================================================================================================
def spec_dict(cfg: Config) -> dict:
    """The frozen spec, emitted into every artefact so a number can always be traced to its model."""
    return dict(m=cfg.m, alpha=cfg.alpha, beta=cfg.beta, gamma=cfg.gamma, Q0=cfg.Q0,
                eta_r=cfg.eta_r, cs=cfg.cs, N_obs=cfg.N_obs, Nf=cfg.Nf, R=cfg.R,
                omega=cfg.omega, lam=cfg.lam, w0=cfg.w0, margin_frac=cfg.margin_frac,
                phi_refund=cfg.phi_refund, N_audit=cfg.N_audit, psi0=cfg.psi0, psi1=cfg.psi1,
                erosion="exp", appeal="linear",
                b_grid=[float(v) for v in B_GRID],
                policies={k: list(v) for k, v in POLICIES.items()},
                policy_class_size=len(POLICY_CLASS))
